name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch (adjust as needed)

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the programming environment (e.g., Node.js, Python, etc.)
      # Adjust this step based on your project's requirements
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run your code (e.g., build, test, or start the application)
      - name: Run the application
        run: npm run start # Replace with your actual start command